version: '3'

services:
 nginx:
  build: etc/nginx/
  volumes:
   - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
   - "./etc/ssl:/etc/ssl"
   - "./web:/var/www/html"
   - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template" 
  ports:
   - 80:80
  environment:
   - NGINX_HOST=${NGINX_HOST}
  command: 
   /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  restart: always
  depends_on:
   - php
   - mysql
   
 php:
  build: etc/php/
  restart: always
  volumes:
   - "./etc/php/php.ini:/usr/local/etc/php/php.ini"
   - "./etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
   - "./web:/var/www/html"
   
 mysql:
   build: etc/mysql/
   container_name: ${MYSQL_HOST}
   restart: always
   command: --sql_mode=""
   env_file:
   - ".env"
   environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
   - MYSQL_USER=${MYSQL_USER}
   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   ports:
   - "3306:3306"
   volumes:
   - "./data/db/mysql:/var/lib/mysql"
